### ISSUE TITLE
'Path too Long' Errors When Unzipping PWS Windows Archives

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/documentation#256]
It could be helpful for customers to add a _Troubleshooting_ section in the documentation.

For instance, explanations about how to solve _Path too Long_ issue on Windows while unzipping a Windows archive. Oracle provides such kind of explanations:

https://docs.oracle.com/cd/E20881_01/html/E20884/glybj.html

An alternative is to unzip Windows archive on Linux and move unzipped files to Windows machines. 

I have created the issue because a customer asked me the question.

**Comment by fviale** [comment]
Add a pointer on the Web page that redirect to the documentation Troubleshooting section.
