### ISSUE TITLE
ProActive client options are outdated

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/documentation#276]
The documentation list the proactive-client options. Unfortunately, this list is not up to date. For instance, the example given for passing parameters while submitting a workflow with `-s` option is no longer valid:

http://doc.activeeon.com/latest/admin/ProActiveAdminGuide.html#_resource_manager_command_line

Personnally, I think that this list should be removed from the documentation since it is hard to maintain up to date.  Instead, only the manner to display available options using `-h` should be documented.

**Comment by lpellegr** [comment]
@bamedro Can we remove the list of options since they are outdated and never kept up to date? There is an example with `-h` that explains how to get such a list.

**Comment by fviale** [comment]
I agree, it's not very useful to print the output of the proactive-client -h command in the documentation

**Comment by lpellegr** [comment]
It was discussed with Brian during a standup that option listing can be removed from the documentation.
